
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Language;

/** CUP generated class containing symbol constants. */
public class TOK {
  /* terminals */
  public static final int TK_rbrk = 52;
  public static final int RW_switch = 15;
  public static final int TK_comma = 53;
  public static final int TK_dollar = 46;
  public static final int TK_notequ = 37;
  public static final int TK_rbrc = 50;
  public static final int RW_bool = 10;
  public static final int RW_break = 21;
  public static final int TK_lessequ = 38;
  public static final int RW_barG = 5;
  public static final int TK_string = 25;
  public static final int TK_equal = 40;
  public static final int RW_main = 2;
  public static final int RW_newVal = 12;
  public static final int RW_pieG = 6;
  public static final int RW_int = 7;
  public static final int RW_string = 11;
  public static final int RW_for = 18;
  public static final int RW_true = 22;
  public static final int TK_equequ = 36;
  public static final int RW_while = 19;
  public static final int TK_colon = 54;
  public static final int TK_or = 44;
  public static final int RW_void = 3;
  public static final int TK_lpar = 47;
  public static final int TK_uminus = 35;
  public static final int RW_defG = 4;
  public static final int RW_false = 23;
  public static final int RW_do = 20;
  public static final int RW_else = 14;
  public static final int TK_id = 29;
  public static final int TK_double = 28;
  public static final int EOF = 0;
  public static final int RW_print = 24;
  public static final int TK_more = 42;
  public static final int error = 1;
  public static final int TK_int = 27;
  public static final int TK_lbrk = 51;
  public static final int RW_double = 8;
  public static final int TK_mult = 33;
  public static final int TK_lbrc = 49;
  public static final int TK_not = 45;
  public static final int TK_and = 43;
  public static final int TK_char = 26;
  public static final int TK_semicolon = 55;
  public static final int TK_inc = 30;
  public static final int TK_div = 34;
  public static final int TK_less = 41;
  public static final int RW_default = 17;
  public static final int TK_moreequ = 39;
  public static final int RW_char = 9;
  public static final int TK_rpar = 48;
  public static final int RW_if = 13;
  public static final int TK_minus = 32;
  public static final int RW_case = 16;
  public static final int TK_plus = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RW_main",
  "RW_void",
  "RW_defG",
  "RW_barG",
  "RW_pieG",
  "RW_int",
  "RW_double",
  "RW_char",
  "RW_bool",
  "RW_string",
  "RW_newVal",
  "RW_if",
  "RW_else",
  "RW_switch",
  "RW_case",
  "RW_default",
  "RW_for",
  "RW_while",
  "RW_do",
  "RW_break",
  "RW_true",
  "RW_false",
  "RW_print",
  "TK_string",
  "TK_char",
  "TK_int",
  "TK_double",
  "TK_id",
  "TK_inc",
  "TK_plus",
  "TK_minus",
  "TK_mult",
  "TK_div",
  "TK_uminus",
  "TK_equequ",
  "TK_notequ",
  "TK_lessequ",
  "TK_moreequ",
  "TK_equal",
  "TK_less",
  "TK_more",
  "TK_and",
  "TK_or",
  "TK_not",
  "TK_dollar",
  "TK_lpar",
  "TK_rpar",
  "TK_lbrc",
  "TK_rbrc",
  "TK_lbrk",
  "TK_rbrk",
  "TK_comma",
  "TK_colon",
  "TK_semicolon"
  };
}

