
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Language;

/** CUP generated class containing symbol constants. */
public class TOK {
  /* terminals */
  public static final int RW_switch = 11;
  public static final int TK_notequ = 33;
  public static final int TK_rbrc = 45;
  public static final int RW_bool = 7;
  public static final int RW_break = 17;
  public static final int TK_lessequ = 34;
  public static final int TK_string = 21;
  public static final int TK_equal = 36;
  public static final int RW_main = 2;
  public static final int RW_int = 4;
  public static final int RW_string = 8;
  public static final int RW_for = 14;
  public static final int RW_true = 18;
  public static final int RW_while = 15;
  public static final int TK_equequ = 32;
  public static final int TK_colon = 46;
  public static final int TK_or = 40;
  public static final int RW_void = 3;
  public static final int TK_lpar = 42;
  public static final int TK_uminus = 31;
  public static final int RW_false = 19;
  public static final int RW_do = 16;
  public static final int RW_else = 10;
  public static final int TK_id = 25;
  public static final int TK_double = 24;
  public static final int EOF = 0;
  public static final int RW_print = 20;
  public static final int TK_more = 38;
  public static final int error = 1;
  public static final int TK_int = 23;
  public static final int RW_double = 5;
  public static final int TK_mult = 29;
  public static final int TK_lbrc = 44;
  public static final int TK_not = 41;
  public static final int TK_and = 39;
  public static final int TK_char = 22;
  public static final int TK_semicolon = 47;
  public static final int TK_inc = 26;
  public static final int TK_div = 30;
  public static final int TK_less = 37;
  public static final int RW_default = 13;
  public static final int TK_moreequ = 35;
  public static final int RW_char = 6;
  public static final int TK_rpar = 43;
  public static final int RW_if = 9;
  public static final int TK_minus = 28;
  public static final int RW_case = 12;
  public static final int TK_plus = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RW_main",
  "RW_void",
  "RW_int",
  "RW_double",
  "RW_char",
  "RW_bool",
  "RW_string",
  "RW_if",
  "RW_else",
  "RW_switch",
  "RW_case",
  "RW_default",
  "RW_for",
  "RW_while",
  "RW_do",
  "RW_break",
  "RW_true",
  "RW_false",
  "RW_print",
  "TK_string",
  "TK_char",
  "TK_int",
  "TK_double",
  "TK_id",
  "TK_inc",
  "TK_plus",
  "TK_minus",
  "TK_mult",
  "TK_div",
  "TK_uminus",
  "TK_equequ",
  "TK_notequ",
  "TK_lessequ",
  "TK_moreequ",
  "TK_equal",
  "TK_less",
  "TK_more",
  "TK_and",
  "TK_or",
  "TK_not",
  "TK_lpar",
  "TK_rpar",
  "TK_lbrc",
  "TK_rbrc",
  "TK_colon",
  "TK_semicolon"
  };
}

