
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Language;

/** CUP generated class containing symbol constants. */
public class TOKJSON {
  /* terminals */
  public static final int TK_double = 3;
  public static final int TK_string = 2;
  public static final int TK_lbrc = 4;
  public static final int error = 1;
  public static final int TK_colon = 7;
  public static final int TK_rbrc = 5;
  public static final int EOF = 0;
  public static final int TK_comma = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_string",
  "TK_double",
  "TK_lbrc",
  "TK_rbrc",
  "TK_comma",
  "TK_colon"
  };
}

